CREATE TABLE public.mmr_participant_metric (
	id bigserial NOT NULL,
	custom_match_id varchar(255) NOT NULL,
	puuid varchar(128) NOT NULL,
	guild_id varchar(128) NOT NULL,
	season varchar(32) NOT NULL,
	champion_id varchar(16) NULL,
	game_team varchar(8) NOT NULL,
	"position" varchar(8) NOT NULL,
	game_result int2 NOT NULL,
	played_date timestamptz NOT NULL,
	kills int4 NULL,
	deaths int4 NULL,
	assists int4 NULL,
	double_kills int4 NULL,
	triple_kills int4 NULL,
	quadra_kills int4 NULL,
	penta_kills int4 NULL,
	killing_sprees int4 NULL,
	largest_killing_spree int4 NULL,
	gold_earned int4 NULL,
	cc_time int4 NULL,
	game_duration int4 NULL,
	damage_to_champions int4 NULL,
	damage_taken int4 NULL,
	damage_self_mitigated int4 NULL,
	vision_score int4 NULL,
	wards_placed int4 NULL,
	wards_killed int4 NULL,
	detector_wards_placed int4 NULL,
	control_wards_bought int4 NULL,
	minions_killed int4 NULL,
	neutral_minions_killed int4 NULL,
	time_spent_dead int4 NULL,
	longest_time_living int4 NULL,
	damage_to_turrets int4 NULL,
	damage_to_objectives int4 NULL,
	dragon_kills int4 NULL,
	baron_kills int4 NULL,
	herald_kills int4 NULL,
	horde_kills int4 NULL,
	last_takedown_time int4 NULL,
	turrets_killed int4 NULL,
	turret_takedowns int4 NULL,
	"level" int4 NULL,
	"exp" int4 NULL,
	turret_plates_destroyed int4 NULL,
	takedowns_under_turret int4 NULL,
	takedowns_before_15min int4 NULL,
	jungle_cs_own int4 NULL,
	jungle_cs_enemy int4 NULL,
	damage_to_epic_monsters int4 NULL,
	objectives_stolen int4 NULL,
	barracks_killed int4 NULL,
	heal_on_teammates int4 NULL,
	shield_on_teammates int4 NULL,
	enemy_missing_pings int4 NULL,
	retreat_pings int4 NULL,
	on_my_way_pings int4 NULL,
	command_pings int4 NULL,
	gold_per_min numeric NULL,
	dpm numeric NULL,
	damage_taken_per_min numeric NULL,
	cc_time_per_min numeric NULL,
	exp_per_min numeric NULL,
	damage_to_turrets_per_min numeric NULL,
	cs_per_min numeric NULL,
	wards_placed_per_min numeric NULL,
	wards_killed_per_min numeric NULL,
	kda numeric NULL,
	damage_taken_per_death numeric NULL,
	damage_dealt_per_death numeric NULL,
	dead_time_pct numeric NULL,
	lane_gold_diff numeric NULL,
	is_mmr_eligible bool DEFAULT true NOT NULL,
	is_deleted bool DEFAULT false NOT NULL,
	create_date timestamptz DEFAULT now() NOT NULL,
	update_date timestamptz DEFAULT now() NOT NULL,
	player_code varchar(64) NULL,
	CONSTRAINT mmr_participant_metric_pkey PRIMARY KEY (id),
	CONSTRAINT uq_mmr_participant_metric_match_puuid UNIQUE (custom_match_id, puuid)
);
CREATE INDEX idx_mpm_custom_match ON public.mmr_participant_metric USING btree (custom_match_id);
CREATE INDEX idx_mpm_guild_player ON public.mmr_participant_metric USING btree (guild_id, player_code);
CREATE INDEX idx_mpm_guild_season_played ON public.mmr_participant_metric USING btree (guild_id, season, played_date DESC);
CREATE INDEX idx_mpm_puuid_season ON public.mmr_participant_metric USING btree (puuid, season);